Databases:
  AISHELL4: wav/{uri}.flac

Protocols:
  AISHELL4:
    SpeakerDiarization:
      Custom:
        scope: file
        train:
          uri: lists/custom_train.txt
          annotation: rttm/{uri}.rttm
          annotated: uem/all.uem
        development:
          uri: lists/custom_dev.txt
          annotation: rttm/{uri}.rttm
          annotated: uem/all.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          annotated: uem/all.uem
      Original:
        scope: file
        train:
          uri: lists/train.txt
          annotation: rttm/{uri}.rttm
          annotated: uem/all.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          annotated: uem/all.uem